Insert cv and param in tracker mode
monome/teletype pull request #285
Opened 2022-05-16 00:56 UTC by mikeyford

#### What does this PR do?
Adds data to patterns using CV input and param values, when in tracker view. Respects settings for IN.SCALE and PARAM.SCALE.

#### Provide links to any related discussion on [lines](https://llllllll.co/).

#### How should this be manually tested?
Go into tracker mode, move param knob while pressing `p`. Supply CV at input while pressing 'i'

#### Any background context you want to provide?
I was looking for quicker way to create sequences from a keyboard with CV out.

#### If the related Github issues aren't referenced in your commits, please link to them here.

#### I have,
* [X] updated `CHANGELOG.md` and `whats_new.md`
* [X] updated the documentation
* [X] updated `help_mode.c` (if applicable)
* [X] run `make format` on each commit
* [X] run tests

2022-05-16 15:35 UTC, tehn requested changes
super cool feature, thanks for adding!

2022-05-16 15:35 UTC, tehn commented on module/help_mode.c
> +                                    "P|SET TO PARAM KNOB" };
also need to modify HELP1_LENGTH const

2022-05-16 19:31 UTC, tehn commented
not sure how i missed the existing functions, thanks for the heads up

On Mon, May 16, 2022, 1:08 PM scanner-darkly ***@***.***>
wrote:

> since we already have ctrl-shift and ctrl-alt to insert param value scaled
> to 0..31 / 0..1023 - is the intent to specifically be able to insert param
> values scaled using PARAM.SCALE?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/monome/teletype/pull/285#issuecomment-1127921540>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB4I4FAN55KGPWWYH5YFHLVKJ6JXANCNFSM5V74YNVQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-05-16 19:37 UTC, scanner-darkly commented
to clarify - currently there is no way to record the input value, just the param value, and i can see the benefit of using PARAM.SCALE in addition to (or maybe as a replacement for?) the predetermined 0..31 / 0..1023 ranges.

2022-05-16 19:38 UTC, mikeyford commented
My primary motivation here was entry from CV. I added the param input option to use the `PARAM.SCALE` values mostly since I was here too. It feels more flexible/useful to me than the existing ranges, but I also don't feel at all strongly about it, so happy to drop it if that's preferred.

2022-05-17 04:10 UTC, scanner-darkly commented
i think both are useful additions since they offer different functionality!

this does bring up a question of using letter shortcuts in tracker view - so far we don’t have any, and i don’t see why there shouldn’t be some, so the question becomes whether we should add a bunch of others to improve tracker functionality (and maybe make it more of an actual tracker), in which case it would be good to consider what else could be added and allocate letters accordingly.

2022-05-17 04:11 UTC, scanner-darkly commented
are you on teletype study discord? we have a dev channel there which is a great place to get quick feedback!

2022-05-17 22:02 UTC, tehn approved these changes

2022-05-17 22:04 UTC, tehn commented
agreed with @scanner-darkly --- before introducing letter input to the tracker screen it'd be good to assess letter assignments more broadly

2022-05-20 03:48 UTC, scanner-darkly commented
perhaps something like shift-p and shift-i for now?

2022-05-20 17:34 UTC, desolationjones commented
I could get behind just changing the existing shortcuts ctrl-alt and ctrl-shift to paste param and in, respectively, scaled to their individual scaling OPs.

Currently:

<html><body>
<!--StartFragment-->

ctrl-alt | insert knob value scaled to 0..31
-- | --
ctrl-shift | insert knob value scaled to 0..1023

<!--EndFragment-->
</body>
</html>

Proposed:
<html><body>
<!--StartFragment-->

ctrl-alt | insert PARAM knob value scaled to `PARAM.SCALE`
-- | --
ctrl-shift | insert `IN` CV value scaled to `IN.SCALE`

<!--EndFragment-->
</body>
</html>

@mikeyford feel free to pop by the [discord study group](https://discord.gg/WsUAhqSb) to discuss!

2022-05-25 16:05 UTC, scanner-darkly commented
i think it's best to keep the existing ones - there might be folks that are used to the old shortcuts, and it would create confusion if people reference the manual but are still on an older version.

2022-05-31 11:52 UTC, mikeyford commented
Apologies. Haven't had time to follow up on this yet, and I'm away from my Teletype for the next few weeks. 

I am planning to join the Discord and discuss this change there once I have time. Also interested/motivated to add further functionality to tracker mode, after collecting some input on the Discord.

2022-07-22 03:48 UTC, closed without merging